import AppKit
import Testing
@testable import SuperclipKit

/// What may and may not be kept.
///
/// The false-positive cases matter as much as the true positives here. A
/// detector that fires on ordinary text trains users to ignore it, so the
/// sentences that merely *begin* with a credential prefix are the load-bearing
/// tests, not the tokens.
@Suite("Sensitive content")
struct SensitiveContentTests {

    @Test("Credential-shaped tokens are refused", arguments: [
        "sk-ant-api03-abc123def456",
        "sk_live_51H8xKjLmNoPqRsTu",
        "ghp_16CharsOfTokenHere0000",
        "github_pat_11ABCDEFG0abcdefgh",
        "AKIAIOSFODNN7EXAMPLE",
        "ASIAY34FZKBOKMUTVV7A",
        "xoxb-123456789-abcdefghij",
        "glpat-xxxxxxxxxxxxxxxxxxxx",
        "AIzaSyD-abcdefghijklmnopqrs",
        "npm_abcdefghijklmnopqrstuvwxyz",
        "-----BEGIN RSA PRIVATE KEY-----\nMIIEow…\n-----END RSA PRIVATE KEY-----"
    ])
    func refusesSecrets(_ text: String) {
        #expect(SensitiveContent.looksLikeSecret(text))
    }

    @Test("Ordinary text is kept", arguments: [
        "412 Kingsway Road, Jalandhar, Punjab 144001",
        "sk- is the prefix Anthropic keys use",
        "AKIA is the prefix for AWS access key IDs",
        "https://github.com/Param077s/superclip/releases",
        "Region\tQ3\tQ4\nNorth\t1200\t1450",
        "param@example.com",
        "+91 98765 43210",
        "The quarterly review is on Thursday at 3pm"
    ])
    func keepsOrdinaryText(_ text: String) {
        #expect(!SensitiveContent.looksLikeSecret(text))
    }

    @Test("Pasteboard privacy markers are honoured", arguments: [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ])
    func honoursMarkers(_ marker: String) {
        let types = [NSPasteboard.PasteboardType(marker), .string]
        #expect(SensitiveContent.isMarkedPrivate(types: types))
        #expect(!SensitiveContent.mayRetain("anything at all", types: types))
    }

    @Test("Plain text with no markers is retained")
    func retainsPlainText() {
        #expect(SensitiveContent.mayRetain("hello", types: [.string]))
    }

    @Test("An empty clip is not a secret")
    func emptyIsNotSecret() {
        #expect(!SensitiveContent.looksLikeSecret(""))
        #expect(!SensitiveContent.looksLikeSecret("   \n  "))
    }
}
