import AppKit

/// What Superclip refuses to retain.
///
/// This is the beginning of the safety layer. Its job is narrow on purpose:
/// catch the credential shapes people actually copy all day and would be alarmed
/// to find sitting in an app's history. It is not, and should not grow into, a
/// general secret scanner — a detector that fires on ordinary text would train
/// users to ignore it.
enum SensitiveContent {

    /// Markers that password managers and similar tools put on the pasteboard.
    /// Honoring these is the established convention on macOS.
    private static let excludedTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    static func isMarkedPrivate(types: [NSPasteboard.PasteboardType]) -> Bool {
        excludedTypes.contains { types.contains(NSPasteboard.PasteboardType($0)) }
    }

    /// Unambiguous credential prefixes. Every entry here is a token format that
    /// no ordinary sentence begins with, so false positives are close to zero.
    private static let credentialPrefixes = [
        "sk-", "sk_live_", "sk_test_", "rk_live_", "pk_live_",
        "ghp_", "gho_", "ghu_", "ghs_", "github_pat_",
        "xoxb-", "xoxp-", "xoxa-", "xapp-",
        "AKIA", "ASIA", "AIza", "ya29.",
        "glpat-", "npm_", "hf_", "dop_v1_", "shpat_",
        "-----BEGIN"
    ]

    static func looksLikeSecret(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }

        // A private key block is the one long-form case worth catching; anything
        // else of that length is prose, not a credential.
        if trimmed.contains("-----BEGIN") && trimmed.contains("PRIVATE KEY") { return true }

        // Credentials are single tokens. Requiring that keeps the prefix check
        // from firing on a sentence that merely starts with "sk-" or a code
        // sample that mentions one.
        guard trimmed.count < 200,
              !trimmed.contains(" "),
              !trimmed.contains("\n") else { return false }

        return credentialPrefixes.contains { trimmed.hasPrefix($0) }
    }

    /// Whether a clip may be kept in the in-memory history.
    static func mayRetain(_ text: String, types: [NSPasteboard.PasteboardType]) -> Bool {
        !isMarkedPrivate(types: types) && !looksLikeSecret(text)
    }
}
